version: '3'
services:
  db:
    image: mariadb:10.0.23
    ports:
      - "42333:3306"
    env_file: .env
  web:
    image: gableroux/rails-webpacker-scss-example
    env_file: .env
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "3035:3035" # webpack-dev-server
    depends_on:
      - db

