default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  port: 3306
  database: <%= ENV['MYSQL_DATABASE'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  pool: 10
